version: '3.8'

services:
  python:
    build: app
    volumes:
      - ./app:/usr/src/app
    tty: true
    depends_on:
      - selenium
  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      TZ: Asia/Tokyo
    ports:
      - '5432:5432'
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres/initdb:/docker-entrypoint-initdb.d
  selenium:
    image: selenium/standalone-firefox:4.1.0-prerelease-20211105
    container_name: selenium-container
    shm_size: 2gb
    ports:
      - '4444:4444'
      - '7900:7900'
    volumes:
      - /dev/shm:/dev/shm